default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fancy_pictures_development

test:
  <<: *default
  host: localhost
  database: fancy_pictures_test
  user: fancy_pictures
  password: fancy_pictures

production:
  <<: *default
