name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop -c .rubocop.yml -f progress

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: fancy_pictures_test
          POSTGRES_USER: fancy_pictures
          POSTGRES_PASSWORD: fancy_pictures
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up test database
        run: |
          bundle exec rails db:migrate:reset
      - name: Run RSpec
        run: |
          bundle exec rspec
